import Head from 'next/head';
import { H1, H2, H3, Button, P } from '../components/elements';


export default function Home(): JSX.Element {
  return (
    <div>
      <Head>
        <title>QTB Korea</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <H1>ABOUT</H1>
        <H2>tese</H2>
        <H3>tese</H3>
        <Button>primary</Button>
        <Button appearance='ghost'>ghost</Button>
        <P>
          There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. 
        </P>
        <P size='s'>
          There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. 
        </P>
        <P size='l'>
          There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. 
        </P>

      </main>

      <footer>
      </footer>
    </div>
  );
}
