import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { H1, H2, H3, Button } from '../components/widgets';


export default function Home(): JSX.Element {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <H1>tese</H1>
        <H2>tese</H2>
        <H3>tese</H3>
        <Button>primary</Button>
        <Button appearance='ghost'>ghost</Button>

      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  );
}
